
format = "[<U+E0B6>](bg:#030B16 fg:#7DF9AA)[<U+F033D> $username@$hostname$nix_shell ](bg:#7DF9AA fg:#090c0c)[<U+E0B0>](fg:#7DF9AA bg:#1C3A5E)$time[<U+E0B0>](fg:#1C3A5E bg:#3B76F0)$container$directory[<U+E0B0>](fg:#3B76F0 bg:#FCF392)$git_branch$git_state$git_status[<U+E0B0>](fg:#FCF392 bg:#030B16)$character"
[character]
error_symbol = "[ ✗](#E84D44) "
success_symbol = "[ ➜](bold green) "

[cmd_duration]
format = "[ <U+F64F> $duration ]($style)"
min_time_to_notify = "60_000"
show_notifications = true
style = "fg:bright-white bg:18"

[container]
format = "[$symbol $name]($style)"
style = "fg:#E4E4E4 bg:#3B76F0"

[directory]
format = "[$read_only$path ]($style)"
read_only = " <U+EA75> "
style = "fg:#E4E4E4 bg:#3B76F0"
truncate_to_repo = false
truncation_length = 4

[fill]
symbol = " "

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "fg:#1C3A5E bg:#FCF392"
symbol = " <U+F418> "

[git_state]
format = "[<$state( $progress_current/$progress_total)>]($style)"
style = "fg:#1C3A5E bg:#FCF392"

[git_status]
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇡$ahead_count⇣$behind_count"
format = "[$all_status$ahead_behind]($style)"
stashed = "<U+F487> "
style = "fg:#1C3A5E bg:#FCF392"
untracked = "<U+EBC3> "

[hostname]
disabled = false
format = "[$hostname$ssh_symbol]($style)"
ssh_only = false
ssh_symbol = " <U+F08B9>'"
style = "bg:#7DF9AA fg:#090c0c"

[nix_shell]
disabled = false
format = " ❄"
heuristic = true
style = "bg:#7DF9AA fg:#090c0c"

[time]
disabled = false
format = "[[ <U+F144D> $time ](bg:#1C3A5E fg:#8DFBD2)]($style)"
style = "bg:#1d2230"
time_format = "%T"

[username]
disabled = false
format = "[$user]($style)"
show_always = true
style_root = "bg:#7DF9AA fg:yellow"
style_user = "bg:#7DF9AA fg:#090c0c"