
name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write  # needed for creating GitHub Releases

jobs:
  build-test-release-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          server-id: 'central'
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Build and test
        run: mvn -B -ntp clean verify -Drevision="${GITHUB_REF_NAME}"
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Create GitHub Release and upload jars
        uses: softprops/action-gh-release@v2
        with:
          files: |
            validator/target/*.jar
            jackson/target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Maven Central
        run: mvn -B -ntp -DskipTests=true deploy -Drevision="${GITHUB_REF_NAME}" -Pgpg-sign
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Print success message
        run: |
          echo "✅ Successfully released ${GITHUB_REF_NAME}"
          echo "✅ GitHub Release created with artifacts"
          echo "✅ Published to Maven Central"
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}